### ISSUE TITLE
App license?

### ISSUE THREAD

**Issue by gentooza** [coopdevs/timeoverflow-mobile-app#11]
Hi!

I see no license in source code

which one is your preferred? Are you planning to license the code?

cheers

**Comment by sseerrggii** [comment]
Hi @gentooza 

Thanks for your help!!  I think should be same license as TimeOveflow https://github.com/coopdevs/timeoverflow/blob/develop/UNLICENSE the app it's only a webview of timeoverflow and adds push notifications feature.

What do you think?

**Comment by sseerrggii** [comment]
I already add it https://github.com/coopdevs/timeoverflow-mobile-app/blob/master/LICENSE

**Comment by gentooza** [comment]
Hi @sseerrggii !

cool, well, I've just learned by other project I'm working on, [that public domain can be problematic in some countries](https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense), as it is not a specific license.

If you don't care about Copyleft, Why not licensing the app under an Apache 2.0 license? [it's recommended by the FSF for mobile phone apps licensing due it's software patents protection](https://www.gnu.org/licenses/license-list.en.html#apache2)

[And the licensing process is very similar](https://apache.org/licenses/LICENSE-2.0), only a LICENSE file in the root directory, and an optional NOTICE file with copyright holders and some specific licenses of third parties, etc. 

Cheers, and thanks for licensing the app!

**Comment by sseerrggii** [comment]
Yes!! Also we are considering changing licenses of TimeOverflow and TimeOverflow-mobile-app to AGPL3 , what do you think?

**Comment by gentooza** [comment]
Cool,

I'd prefer this, also.

The licensing process is a little bit more complicated (copyright headers in every file...), and the implications. (public link with the actual code repository available in app) I'd be interested on helping you!

cheers

**Comment by sseerrggii** [comment]
Yes, thankyou for your help @gentooza :)

We should wait to @sauloperez that is working on a new update of the app https://github.com/sauloperez/my-app and after that we can update what we need for AGPL3 license
